from scripts.objects.chandelier import Chandelier
from scripts.objects.door import Door
from scripts.objects.ending_door import EndingDoor
from scripts.objects.table import Table
from scripts.objects.table_lamp import TableLamp
from scripts.objects.key import Key
from scripts.objects.small_table import SmallTable
from scripts.objects.leather_chair import LeatherChair
from scripts.objects.table_ornement import TableOrnement
from scripts.objects.pillar import Pillar
from scripts.objects.plant import Plant
from scripts.objects.room_center import RoomCenter
from scripts.objects.wooden_chair import WoodenChair
from scripts.objects.bookshelf import Bookshelf
from scripts.objects.george import George
from scripts.objects.closet import Closet
from scripts.objects.clock import Clock
